server:
  port: 4000
spring:
  application:
    name: crowd-authentication
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: 8.130.22.91
  session:
    store-type: redis
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka